-- Initial Data for Interview Prep Platform - Extended Edition
-- NOTE: All timestamps use CURRENT_TIMESTAMP for H2 compatibility

-- Insert Roles (31 roles for comprehensive coverage)
INSERT INTO roles (name, summary, core_skills, interview_focus_areas, created_at, updated_at)
SELECT * FROM (VALUES
    ('Java Developer', 'Build and scale backend systems with Java, Spring, and relational data stores.', 
     '["Java","Spring","Spring Boot","SQL","Microservices","REST APIs"]',
     '["coding","system design","debugging","API design","performance","ownership"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Python Developer', 'Develop automation, APIs, analytics workflows, and ML-adjacent services in Python.', 
     '["Python","FastAPI","Flask","Pandas","SQL","Automation"]',
     '["problem solving","backend design","data handling","testing","scripting","ownership"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Full Stack Developer', 'Ship end-to-end product features across frontend, backend, API, and database layers.', 
     '["React","TypeScript","Java","Spring","PostgreSQL","REST APIs"]',
     '["feature design","cross-functional delivery","trade-offs","testing","scalability","UX awareness"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Data Analyst', 'Turn messy data into useful decisions through analysis, dashboards, and stakeholder communication.', 
     '["Python","SQL","Analytics","Statistics","Visualization","Dashboards"]',
     '["data storytelling","metric design","business context","SQL depth","insight communication","prioritization"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('DevOps Engineer', 'Improve deployment speed, reliability, and observability across infrastructure and delivery pipelines.', 
     '["Docker","Kubernetes","AWS","Terraform","CI/CD","Linux"]',
     '["incident response","automation","observability","resilience","cost-awareness","platform thinking"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Frontend Engineer', 'Create performant, usable, and maintainable interfaces across modern web applications.', 
     '["React","TypeScript","JavaScript","HTML","CSS","Tailwind CSS"]',
     '["UI architecture","performance","accessibility","state management","testing","product thinking"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Backend Engineer', 'Design stable backend services, data models, and integration-heavy application layers.', 
     '["Java","Spring","PostgreSQL","REST APIs","Microservices","SQL"]',
     '["API design","data modeling","performance","resilience","debugging","trade-offs"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Data Scientist', 'Build predictive models, run experiments, and deliver machine learning solutions that drive business decisions.', 
     '["Python","Machine Learning","Statistics","TensorFlow","PyTorch","Data Analysis"]',
     '["model building","experimentation","statistical thinking","ML ops","communication","business impact"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Machine Learning Engineer', 'Deploy scalable ML systems and optimize model performance in production environments.', 
     '["Python","TensorFlow","PyTorch","MLOps","Kubernetes","Cloud Platforms"]',
     '["model deployment","scalability","performance optimization","monitoring","system design","experimentation"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cloud Architect', 'Design and implement cloud infrastructure solutions with focus on scalability, security, and cost optimization.', 
     '["AWS","Azure","GCP","Terraform","Cloud Security","Architecture Design"]',
     '["system design","security","cost optimization","scalability","migration strategies","governance"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Site Reliability Engineer', 'Ensure system reliability, performance, and availability through automation and proactive monitoring.', 
     '["Kubernetes","Docker","Prometheus","Grafana","Python","Go"]',
     '["incident management","automation","monitoring","capacity planning","post-mortems","on-call"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Security Engineer', 'Protect systems and data through security architecture, threat modeling, and vulnerability management.', 
     '["Security","Penetration Testing","OWASP","Cryptography","Network Security","Compliance"]',
     '["threat modeling","vulnerability assessment","incident response","secure coding","compliance","risk management"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Product Manager', 'Define product strategy, prioritize features, and drive cross-functional teams to deliver customer value.', 
     '["Product Strategy","Roadmapping","User Research","Data Analysis","Stakeholder Management","Agile"]',
     '["strategic thinking","prioritization","communication","user empathy","decision making","metrics"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('UX Designer', 'Create intuitive user experiences through research, wireframing, prototyping, and usability testing.', 
     '["Figma","User Research","Wireframing","Prototyping","Usability Testing","Design Systems"]',
     '["user empathy","visual design","interaction design","research methods","collaboration","iteration"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('UI Developer', 'Implement pixel-perfect interfaces with focus on responsiveness, accessibility, and performance.', 
     '["HTML","CSS","JavaScript","React","Vue","Responsive Design"]',
     '["CSS mastery","responsive design","accessibility","performance","cross-browser","attention to detail"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Mobile Developer', 'Build native or cross-platform mobile applications for iOS and Android platforms.', 
     '["React Native","Flutter","Swift","Kotlin","Mobile UI","API Integration"]',
     '["mobile development","platform guidelines","performance","offline support","app lifecycle","testing"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('QA Engineer', 'Ensure software quality through test planning, automation, and comprehensive quality assurance practices.', 
     '["Automation Testing","Selenium","Jest","Cypress","Test Planning","Bug Tracking"]',
     '["test strategy","automation","attention to detail","communication","debugging","quality mindset"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Database Administrator', 'Manage database systems ensuring performance, security, backup, and recovery procedures.', 
     '["PostgreSQL","MySQL","MongoDB","Database Tuning","Backup","Security"]',
     '["performance tuning","disaster recovery","security","query optimization","capacity planning","monitoring"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Business Analyst', 'Bridge business needs and technical solutions through requirements gathering and process analysis.', 
     '["Requirements Analysis","SQL","Business Process","Documentation","Stakeholder Management","JIRA"]',
     '["analytical thinking","communication","documentation","process mapping","stakeholder management","problem solving"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Scrum Master', 'Facilitate agile teams, remove blockers, and ensure smooth sprint execution and continuous improvement.', 
     '["Agile","Scrum","JIRA","Facilitation","Coaching","Team Building"]',
     '["facilitation","conflict resolution","coaching","metrics","ceremonies","servant leadership"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Technical Writer', 'Create clear documentation, API guides, and user manuals for technical products and services.', 
     '["Technical Writing","Documentation","API Documentation","Markdown","Git","Content Management"]',
     '["clarity","audience awareness","technical understanding","structure","collaboration","tool proficiency"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Solutions Architect', 'Design end-to-end technical solutions aligning business requirements with technology capabilities.', 
     '["System Design","Cloud Architecture","Integration Patterns","Microservices","API Design","Enterprise Architecture"]',
     '["holistic thinking","trade-off analysis","communication","technology breadth","business alignment","scalability"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Blockchain Developer', 'Build decentralized applications and smart contracts on blockchain platforms.', 
     '["Solidity","Ethereum","Web3","Smart Contracts","Cryptography","Blockchain Architecture"]',
     '["blockchain fundamentals","smart contract security","gas optimization","DApp development","consensus","testing"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Game Developer', 'Create engaging gaming experiences through game mechanics, graphics, and performance optimization.', 
     '["Unity","Unreal Engine","C#","C++","Game Physics","3D Graphics"]',
     '["game mechanics","performance optimization","graphics programming","player experience","debugging","creativity"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('AI Engineer', 'Develop artificial intelligence solutions including NLP, computer vision, and generative AI applications.', 
     '["Deep Learning","NLP","Computer Vision","Transformers","OpenAI","LangChain"]',
     '["model selection","fine-tuning","prompt engineering","evaluation","deployment","ethical AI"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Data Engineer', 'Build and maintain data pipelines, warehouses, and infrastructure for analytics and ML workloads.', 
     '["Apache Spark","Airflow","SQL","Python","Data Warehousing","ETL"]',
     '["pipeline design","data quality","performance","scalability","orchestration","data modeling"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Cybersecurity Analyst', 'Monitor, detect, and respond to security threats while maintaining security posture.', 
     '["SIEM","Threat Detection","Incident Response","Network Security","Firewalls","Vulnerability Management"]',
     '["threat analysis","incident handling","security tools","compliance","forensics","risk assessment"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('iOS Developer', 'Develop native iOS applications using Swift and Apple development frameworks.', 
     '["Swift","SwiftUI","UIKit","Xcode","iOS SDK","App Store"]',
     '["iOS development","Apple guidelines","performance","memory management","testing","App Store submission"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Android Developer', 'Create native Android applications using Kotlin and Android development tools.', 
     '["Kotlin","Android SDK","Jetpack Compose","Android Studio","Material Design","Play Store"]',
     '["Android development","Material Design","performance","compatibility","testing","Play Store guidelines"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Engineering Manager', 'Lead engineering teams, manage technical projects, and drive team growth and performance.', 
     '["Team Leadership","Project Management","Technical Strategy","Hiring","Performance Management","Agile"]',
     '["people management","strategic thinking","delegation","conflict resolution","career development","technical depth"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Platform Engineer', 'Build internal developer platforms and tools that improve engineering productivity and workflow.', 
     '["Kubernetes","Docker","CI/CD","Infrastructure as Code","Developer Tools","Automation"]',
     '["platform thinking","developer experience","automation","scalability","documentation","feedback loops"]', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
) AS temp_roles;
